version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies (if any)..."
  build:
    commands:
      - echo "Building project..."
  post_build:
    commands:
      - echo "Build complete. Uploading to S3..."
      - aws s3 sync . s3://okstateawsjira --delete

artifacts:
  files:
    - '**/*'
